services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html    
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=${ENV}
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

  frontend: 
      build:
        context: ./frontend
      volumes:
        - ./frontend:/usr/src/app 
      environment:
        - REACT_APP_DOMAIN_API=${DOMAIN_API}
        - REACT_APP_DOMAIN=${DOMAIN}
        - REACT_APP_ENV=${ENV} 
      healthcheck:
        test: "netstat -tulpn | grep 3000"
        interval: 30s
        timeout: 10s
        retries: 5

  backend:
    build:
      context: ./backend
    volumes: 
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
      - .env
    healthcheck:
        test: "netstat -tulpn | grep 3000"
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: ./mariadb.config
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - ./backend/.env
    healthcheck:
      test: "mariadb -h localhost -u$$MARIADB_USER -p$$MARIADB_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 5s
      retries: 10
