services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html    
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=${ENV}

##### DEVELOPMENT  MODE ####
#  frontend: 
#    build:
#      context: ./frontend
#    volumes:
#      - ./frontend:/usr/src/app #dev
#    ports:
#      - 8080:8080 #dev
#    environment:
#      - REACT_APP_API_URI=${API_URI}
#      - REACT_APP_DOMAIN_URI=${DOMAIN_URI}
#      - PORT=8080 
#      - REACT_APP_DEV_MODE=true 


##### PRODUCTION  MODE ####
  frontend: 
      build:
        context: ./frontend
      volumes:
        - ./frontend:/usr/src/app 
      environment:
        - REACT_APP_DOMAIN_API=${DOMAIN_API}
        - REACT_APP_DOMAIN=${DOMAIN}
        - REACT_APP_ENV=${ENV} 


##### DEVELOPMENT  MODE ####
#  backend:
#    build:
#      context: ./backend
#    volumes: 
#      - ./backend:/usr/src/app
#    ports: # dev
#      - 3000:3000 #dev
#    env_file:
#      - ./backend/.env
#      - .env
#    depends_on:
#      mariadb:
#        condition: service_healthy


##### PRODUCTION  MODE ####
  backend:
    build:
      context: ./backend
    volumes: 
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: ./mariadb.config
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - ./backend/.env
    healthcheck:
      test: "mariadb -h localhost -u$$MARIADB_USER -p$$MARIADB_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 5s
      retries: 10
