FROM nginx

COPY matcha.conf /etc/nginx/conf.d/matcha.conf

COPY fullchain.pem /etc/letsencrypt/live/matcha.mezyann.fr/fullchain.pem

COPY privkey.pem /etc/letsencrypt/live/matcha.mezyann.fr/privkey.pem
