server {
	listen 80;
	listen [::]:80;
	server_name _;
	return 301 https://$host$request_uri;
}


server {
	listen 443 default_server ssl;
	listen [::]:443 default_server ssl;

	server_name matcha.mezyann.fr;

	ssl_certificate /etc/letsencrypt/live/matcha.mezyann.fr/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/matcha.mezyann.fr/privkey.pem;

	client_max_body_size 10m;

	root /usr/share/nginx/html;

	location /socket.io/ {
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;

		proxy_pass http://backend:3000;

		#proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	
	location /api {
		proxy_pass http://backend:3000/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /api/ {
		proxy_pass http://backend:3000/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location / {
		try_files $uri $uri/ /index.html =404;
	}

}
